export const size = {
  mobileS: "320px",
  mobileM: "375px",
  mobileL: "425px",
  tablet: "768px",
  laptop: "1024px",
  laptopL: "1440px",
  desktop: "2560px",
};

export const device = {
  mobileS: `(max-width: ${size.mobileS})`,
  mobileM: `(max-width: ${size.mobileM})`,
  mobileL: `(max-width: ${size.mobileL})`,
  tablet: `(max-width: ${size.tablet})`,
  laptop: `(max-width: ${size.laptop})`,
  laptopL: `(max-width: ${size.laptopL})`,
  desktop: `(max-width: ${size.desktop})`,
  desktopL: `(max-width: ${size.desktop})`,
};

export const country = [
  { value: "unselect", label: "--- unselect ---", id: 0 },
  { value: "United States", label: "United States", id: 1 },
  { value: "United Kingdom", label: "United Kingdom", id: 2 },
  { value: "India", label: "India", id: 3 },
  { value: "Afghanistan", label: "Afghanistan", id: 4 },
  { value: "Albania", label: "Albania", id: 5 },
  { value: "Algeria", label: "Algeria", id: 6 },
  { value: "American Samoa", label: "American Samoa", id: 7 },
  { value: "Andorra", label: "Andorra", id: 8 },
  { value: "Angola", label: "Angola", id: 9 },
  { value: "Anguilla", label: "Anguilla", id: 10 },
  { value: "Antigua & Barbuda", label: "Antigua & Barbuda", id: 11 },
  { value: "Argentina", label: "Argentina", id: 12 },
  { value: "Armenia", label: "Armenia", id: 13 },
  { value: "Aruba", label: "Aruba", id: 14 },
  { value: "Australia", label: "Australia", id: 15 },
  { value: "Austria", label: "Austria", id: 16 },
  { value: "Azerbaijan", label: "Azerbaijan", id: 17 },
  { value: "Bahamas", label: "Bahamas", id: 18 },
  { value: "Bahrain", label: "Bahrain", id: 19 },
  { value: "Bangladesh", label: "Bangladesh", id: 20 },
  { value: "Barbados", label: "Barbados", id: 21 },
  { value: "Belarus", label: "Belarus", id: 22 },
  { value: "Belgium", label: "Belgium", id: 23 },
  { value: "Belize", label: "Belize", id: 24 },
  { value: "Benin", label: "Benin", id: 25 },
  { value: "Bermuda", label: "Bermuda", id: 26 },
  { value: "Bhutan", label: "Bhutan", id: 27 },
  { value: "Bolivia", label: "Bolivia", id: 28 },
  { value: "Bonaire", label: "Bonaire", id: 29 },
  { value: "Bosnia & Herzegovina", label: "Bosnia & Herzegovina", id: 30 },
  { value: "Botswana", label: "Botswana", id: 31 },
  { value: "Brazil", label: "Brazil", id: 32 },
  {
    value: "British Indian Ocean Ter",
    label: "British Indian Ocean Ter",
    id: 33,
  },
  { value: "Brunei", label: "Brunei", id: 34 },
  { value: "Bulgaria", label: "Bulgaria", id: 35 },
  { value: "Burkina Faso", label: "Burkina Faso", id: 36 },
  { value: "Burundi", label: "Burundi", id: 37 },
  { value: "Cambodia", label: "Cambodia", id: 38 },
  { value: "Cameroon", label: "Cameroon", id: 39 },
  { value: "Canada", label: "Canada", id: 40 },
  { value: "Canary Islands", label: "Canary Islands", id: 41 },
  { value: "Cape Verde", label: "Cape Verde", id: 42 },
  { value: "Cayman Islands", label: "Cayman Islands", id: 43 },
  {
    value: "Central African Republic",
    label: "Central African Republic",
    id: 44,
  },
  { value: "Chad", label: "Chad", id: 45 },
  { value: "Channel Islands", label: "Channel Islands", id: 46 },
  { value: "Chile", label: "Chile", id: 47 },
  { value: "China", label: "China", id: 48 },
  { value: "Christmas Island", label: "Christmas Island", id: 49 },
  { value: "Cocos Island", label: "Cocos Island", id: 50 },
  { value: "Colombia", label: "Colombia", id: 51 },
  { value: "Comoros", label: "Comoros", id: 52 },
  { value: "Congo", label: "Congo", id: 53 },
  { value: "Cook Islands", label: "Cook Islands", id: 54 },
  { value: "Costa Rica", label: "Costa Rica", id: 55 },
  { value: "Cote DIvoire", label: "Cote DIvoire", id: 56 },
  { value: "Croatia", label: "Croatia", id: 57 },
  { value: "Cuba", label: "Cuba", id: 58 },
  { value: "Curacao", label: "Curacao", id: 59 },
  { value: "Cyprus", label: "Cyprus", id: 60 },
  { value: "Czech Republic", label: "Czech Republic", id: 61 },
  { value: "Denmark", label: "Denmark", id: 62 },
  { value: "Djibouti", label: "Djibouti", id: 63 },
  { value: "Dominica", label: "Dominica", id: 64 },
  { value: "Dominican Republic", label: "Dominican Republic", id: 65 },
  { value: "East Timor", label: "East Timor", id: 66 },
  { value: "Ecuador", label: "Ecuador", id: 67 },
  { value: "Egypt", label: "Egypt", id: 68 },
  { value: "El Salvador", label: "El Salvador", id: 69 },
  { value: "Equatorial Guinea", label: "Equatorial Guinea", id: 70 },
  { value: "Eritrea", label: "Eritrea", id: 71 },
  { value: "Estonia", label: "Estonia", id: 72 },
  { value: "Ethiopia", label: "Ethiopia", id: 73 },
  { value: "Falkland Islands", label: "Falkland Islands", id: 74 },
  { value: "Faroe Islands", label: "Faroe Islands", id: 75 },
  { value: "Fiji", label: "Fiji", id: 76 },
  { value: "Finland", label: "Finland", id: 77 },
  { value: "France", label: "France", id: 78 },
  { value: "French Guiana", label: "French Guiana", id: 79 },
  { value: "French Polynesia", label: "French Polynesia", id: 80 },
  { value: "French Southern Ter", label: "French Southern Ter", id: 81 },
  { value: "Gabon", label: "Gabon", id: 82 },
  { value: "Gambia", label: "Gambia", id: 83 },
  { value: "Georgia", label: "Georgia", id: 84 },
  { value: "Germany", label: "Germany", id: 85 },
  { value: "Ghana", label: "Ghana", id: 86 },
  { value: "Gibraltar", label: "Gibraltar", id: 87 },
  { value: "Great Britain", label: "Great Britain", id: 88 },
  { value: "Greece", label: "Greece", id: 89 },
  { value: "Greenland", label: "Greenland", id: 90 },
  { value: "Grenada", label: "Grenada", id: 91 },
  { value: "Guadeloupe", label: "Guadeloupe", id: 92 },
  { value: "Guam", label: "Guam", id: 93 },
  { value: "Guatemala", label: "Guatemala", id: 94 },
  { value: "Guinea", label: "Guinea", id: 95 },
  { value: "Guyana", label: "Guyana", id: 96 },
  { value: "Haiti", label: "Haiti", id: 97 },
  { value: "Hawaii", label: "Hawaii", id: 98 },
  { value: "Honduras", label: "Honduras", id: 99 },
  { value: "Hong Kong", label: "Hong Kong", id: 100 },
  { value: "Hungary", label: "Hungary", id: 101 },
  { value: "Iceland", label: "Iceland", id: 102 },
  { value: "Indonesia", label: "Indonesia", id: 103 },
  { value: "Iran", label: "Iran", id: 104 },
  { value: "Iraq", label: "Iraq", id: 105 },
  { value: "Ireland", label: "Ireland", id: 106 },
  { value: "Isle of Man", label: "Isle of Man", id: 107 },
  { value: "Israel", label: "Israel", id: 108 },
  { value: "Italy", label: "Italy", id: 109 },
  { value: "Jamaica", label: "Jamaica", id: 110 },
  { value: "Japan", label: "Japan", id: 111 },
  { value: "Jordan", label: "Jordan", id: 112 },
  { value: "Kazakhstan", label: "Kazakhstan", id: 113 },
  { value: "Kenya", label: "Kenya", id: 114 },
  { value: "Kiribati", label: "Kiribati", id: 115 },
  { value: "Korea North", label: "Korea North", id: 116 },
  { value: "Korea South", label: "Korea South", id: 117 },
  { value: "Kuwait", label: "Kuwait", id: 118 },
  { value: "Kyrgyzstan", label: "Kyrgyzstan", id: 119 },
  { value: "Laos", label: "Laos", id: 120 },
  { value: "Latvia", label: "Latvia", id: 121 },
  { value: "Lebanon", label: "Lebanon", id: 122 },
  { value: "Lesotho", label: "Lesotho", id: 123 },
  { value: "Liberia", label: "Liberia", id: 124 },
  { value: "Libya", label: "Libya", id: 125 },
  { value: "Liechtenstein", label: "Liechtenstein", id: 126 },
  { value: "Lithuania", label: "Lithuania", id: 127 },
  { value: "Luxembourg", label: "Luxembourg", id: 128 },
  { value: "Macau", label: "Macau", id: 129 },
  { value: "Macedonia", label: "Macedonia", id: 130 },
  { value: "Madagascar", label: "Madagascar", id: 131 },
  { value: "Malaysia", label: "Malaysia", id: 132 },
  { value: "Malawi", label: "Malawi", id: 133 },
  { value: "Maldives", label: "Maldives", id: 134 },
  { value: "Mali", label: "Mali", id: 135 },
  { value: "Malta", label: "Malta", id: 136 },
  { value: "Marshall Islands", label: "Marshall Islands", id: 137 },
  { value: "Martinique", label: "Martinique", id: 138 },
  { value: "Mauritania", label: "Mauritania", id: 139 },
  { value: "Mauritius", label: "Mauritius", id: 140 },
  { value: "Mayotte", label: "Mayotte", id: 141 },
  { value: "Mexico", label: "Mexico", id: 142 },
  { value: "Midway Islands", label: "Midway Islands", id: 143 },
  { value: "Moldova", label: "Moldova", id: 144 },
  { value: "Monaco", label: "Monaco", id: 145 },
  { value: "Mongolia", label: "Mongolia", id: 146 },
  { value: "Montserrat", label: "Montserrat", id: 147 },
  { value: "Morocco", label: "Morocco", id: 148 },
  { value: "Mozambique", label: "Mozambique", id: 149 },
  { value: "Myanmar", label: "Myanmar", id: 150 },
  { value: "Nambia", label: "Nambia", id: 151 },
  { value: "Nauru", label: "Nauru", id: 152 },
  { value: "Nepal", label: "Nepal", id: 153 },
  { value: "Netherland Antilles", label: "Netherland Antilles", id: 154 },
  {
    value: "Netherlands (Holland, Europe)",
    label: "Netherlands (Holland, Europe)",
    id: 155,
  },
  { value: "Nevis", label: "Nevis", id: 156 },
  { value: "New Caledonia", label: "New Caledonia", id: 157 },
  { value: "New Zealand", label: "New Zealand", id: 158 },
  { value: "Nicaragua", label: "Nicaragua", id: 159 },
  { value: "Niger", label: "Niger", id: 160 },
  { value: "Nigeria", label: "Nigeria", id: 161 },
  { value: "Niue", label: "Niue", id: 162 },
  { value: "Norfolk Island", label: "Norfolk Island", id: 163 },
  { value: "Norway", label: "Norway", id: 164 },
  { value: "Oman", label: "Oman", id: 165 },
  { value: "Pakistan", label: "Pakistan", id: 166 },
  { value: "Palau Island", label: "Palau Island", id: 167 },
  { value: "Palestine", label: "Palestine", id: 168 },
  { value: "Panama", label: "Panama", id: 169 },
  { value: "Papua New Guinea", label: "Papua New Guinea", id: 170 },
  { value: "Paraguay", label: "Paraguay", id: 171 },
  { value: "Peru", label: "Peru", id: 172 },
  { value: "Philippines", label: "Philippines", id: 173 },
  { value: "Pitcairn Island", label: "Pitcairn Island", id: 174 },
  { value: "Poland", label: "Poland", id: 175 },
  { value: "Portugal", label: "Portugal", id: 176 },
  { value: "Puerto Rico", label: "Puerto Rico", id: 177 },
  { value: "Qatar", label: "Qatar", id: 178 },
  { value: "Republic of Montenegro", label: "Republic of Montenegro", id: 179 },
  { value: "Republic of Serbia", label: "Republic of Serbia", id: 180 },
  { value: "Reunion", label: "Reunion", id: 181 },
  { value: "Romania", label: "Romania", id: 182 },
  { value: "Russia", label: "Russia", id: 183 },
  { value: "Rwanda", label: "Rwanda", id: 184 },
  { value: "St Barthelemy", label: "St Barthelemy", id: 185 },
  { value: "St Eustatius", label: "St Eustatius", id: 186 },
  { value: "St Helena", label: "St Helena", id: 187 },
  { value: "St Kitts-Nevis", label: "St Kitts-Nevis", id: 188 },
  { value: "St Lucia", label: "St Lucia", id: 189 },
  { value: "St Maarten", label: "St Maarten", id: 190 },
  { value: "St Pierre & Miquelon", label: "St Pierre & Miquelon", id: 191 },
  {
    value: "St Vincent & Grenadines",
    label: "St Vincent & Grenadines",
    id: 192,
  },
  { value: "Saipan", label: "Saipan", id: 193 },
  { value: "Samoa", label: "Samoa", id: 194 },
  { value: "Samoa American", label: "Samoa American", id: 195 },
  { value: "San Marino", label: "San Marino", id: 196 },
  { value: "Sao Tome & Principe", label: "Sao Tome & Principe", id: 197 },
  { value: "Saudi Arabia", label: "Saudi Arabia", id: 198 },
  { value: "Senegal", label: "Senegal", id: 199 },
  { value: "Seychelles", label: "Seychelles", id: 200 },
  { value: "Sierra Leone", label: "Sierra Leone", id: 201 },
  { value: "Singapore", label: "Singapore", id: 202 },
  { value: "Slovakia", label: "Slovakia", id: 203 },
  { value: "Slovenia", label: "Slovenia", id: 204 },
  { value: "Solomon Islands", label: "Solomon Islands", id: 205 },
  { value: "Somalia", label: "Somalia", id: 206 },
  { value: "South Africa", label: "South Africa", id: 207 },
  { value: "Spain", label: "Spain", id: 208 },
  { value: "Sri Lanka", label: "Sri Lanka", id: 209 },
  { value: "Sudan", label: "Sudan", id: 210 },
  { value: "Suriname", label: "Suriname", id: 211 },
  { value: "Swaziland", label: "Swaziland", id: 212 },
  { value: "Sweden", label: "Sweden", id: 213 },
  { value: "Switzerland", label: "Switzerland", id: 214 },
  { value: "Syria", label: "Syria", id: 215 },
  { value: "Tahiti", label: "Tahiti", id: 216 },
  { value: "Taiwan", label: "Taiwan", id: 217 },
  { value: "Tajikistan", label: "Tajikistan", id: 218 },
  { value: "Tanzania", label: "Tanzania", id: 219 },
  { value: "Thailand", label: "Thailand", id: 220 },
  { value: "Togo", label: "Togo", id: 221 },
  { value: "Tokelau", label: "Tokelau", id: 222 },
  { value: "Tonga", label: "Tonga", id: 223 },
  { value: "Trinidad & Tobago", label: "Trinidad & Tobago", id: 224 },
  { value: "Tunisia", label: "Tunisia", id: 225 },
  { value: "Turkey", label: "Turkey", id: 226 },
  { value: "Turkmenistan", label: "Turkmenistan", id: 227 },
  { value: "Turks & Caicos Is", label: "Turks & Caicos Is", id: 228 },
  { value: "Tuvalu", label: "Tuvalu", id: 229 },
  { value: "Uganda", label: "Uganda", id: 230 },
  { value: "Ukraine", label: "Ukraine", id: 231 },
  { value: "United Arab Emirates", label: "United Arab Emirates", id: 232 },
  { value: "Uruguay", label: "Uruguay", id: 233 },
  { value: "Uzbekistan", label: "Uzbekistan", id: 234 },
  { value: "Vanuatu", label: "Vanuatu", id: 235 },
  { value: "Vatican City State", label: "Vatican City State", id: 236 },
  { value: "Venezuela", label: "Venezuela", id: 237 },
  { value: "Vietnam", label: "Vietnam", id: 238 },
  { value: "Virgin Islands (Brit)", label: "Virgin Islands (Brit)", id: 239 },
  { value: "Virgin Islands (USA)", label: "Virgin Islands (USA)", id: 240 },
  { value: "Wake Island", label: "Wake Island", id: 241 },
  { value: "Wallis & Futana Is", label: "Wallis & Futana Is", id: 242 },
  { value: "Yemen", label: "Yemen", id: 243 },
  { value: "Zaire", label: "Zaire", id: 244 },
  { value: "Zambia", label: "Zambia", id: 245 },
  { value: "Zimbabwe", label: "Zimbabwe", id: 246 },
];

export const staticSecondaryTabs = [
  {
    id: 1,
    label: "Authors",
    isDisabled: false,
    isOutput: false,
  },
  {
    id: 2,
    label: "Properties",
    isDisabled: false,
    isOutput: false,
  },
  {
    id: 3,
    label: "Input",
    isDisabled: false,
    isOutput: false,
  },
];